on:
  push:
    branches:
      - main
jobs:
  automatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Actions IP
        run: |
          ip=`curl https://checkip.amazonaws.com`
          echo $ip
          echo "github_ip=$ip" >> $GITHUB_ENV

      - name: Add Github Actions IP to security group
        run: aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_RDS_WHITELIST_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.github_ip }}/24
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}


      - name: Execute deploy commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.TESTE_HOST }}
          username: ${{ secrets.TESTE_USER }}
          key: ${{ secrets.TESTE_KEY }}
          script:
        
            cd ${{ secrets.TESTE_PATH }}
            wget https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb
            sudo dpkg -i zabbix-release_6.4-1+debian12_all.deb
           sudo apt update -y
            sudo apt install zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent -y
            
      - name: Remove Github Actions IP from security group
        run: aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_RDS_WHITELIST_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.github_ip }}/24
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        if: always()
