on:
  push:
    branches:
      - main
jobs:
  automatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Actions IP
        run: |
          ip=`curl https://checkip.amazonaws.com`
          echo $ip
          echo "github_ip=$ip" >> $GITHUB_ENV

      - name: Add Github Actions IP to security group
        run: aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_RDS_WHITELIST_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.github_ip }}/24
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.TESTE_HOST }}
          remote-user: ${{ secrets.TESTE_USER }}
          private-ssh-key: ${{ secrets.TESTE_KEY }}
          destination-path: ${{ secrets.TESTE_PATH }}
       
      - name: Execute deploy commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.TESTE_HOST }}
          username: ${{ secrets.TESTE_USER }}
          key: ${{ secrets.TESTE_KEY }}
          script: |
            sudo su
                 cd ${{ secrets.TEST_PATH }}
          
  
        
            
            
        

      - name: Remove Github Actions IP from security group
        run: aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_RDS_WHITELIST_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.github_ip }}/24
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        if: always()
